### ISSUE TITLE
Segment Video Recordings

### ISSUE THREAD

**Issue by lookreelDev** [RenderHeads/UnityPlugin-AVProMovieCapture#120]
Hello RenderHeads,

I posting in the feature request because I am not sure whether this feature is available.

I was wandering if there is any options to record video as multiple video streams. Meaning segment the recordings, example 
segment recording every 20 min creating new files.

I looked everywhere to see if this is possible.

Unity version: 2020.3.16f1
AVPro Movie Capture version: 4.6.5
Operating system version: Windows 10

Much obliged!

**Comment by kahnivore** [comment]
Hi there,

We don't explicitly have a feature for this but there's no reason why you couldn't implement this yourself. 

It'd be as simple as calling StopCapture and StartCapture at whatever time interval you require. 

You'd potentially lose a few frames between each video though. 

Does that help?

**Comment by artoonie** [comment]
I want to add my :+1: to this request.

In particular, given the uncertain timeline of #110, this feature would be a nice way to minimize the amount of lost data in the case of a crash. I'd ideally like a new video clip every 60 seconds, which makes lost frames a much bigger deal since they'd be quite noticeable at that frequency.

Alternatively (and let me know if I should open a new ticket for this), it would be nice to have recommendations for how to deal with pausing capture when applications going to the background on iOS. Calling StopCapture() from OnApplicationFocus(false) does too much work and often fails with error:
```
🟩 Capture failed, error: The operation could not be completed
🟩 Underlying error: The operation couldn’t be completed. (OSStatus error -16356.)
🔹 Finished writing
🟩 Failed to remove temp files directory
```

**Comment by kahnivore** [comment]
@artoonie this isn't something we're likely to add, but as said above it shouldn't be difficult to implement this in your own application.
