### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Zhaopengyang** [RenderHeads/UnityPlugin-AVProMovieCapture#244]
![7776E5EF-BD94-487B-BF8A-C2B6890EA604](https://user-images.githubusercontent.com/20550618/215319252-ceef4584-9f90-4469-a2ad-5012e52f4a31.png)
Fix Please!!!

**Comment by Chris-RH** [comment]
Hi @Zhaopengyang,
Please can you complete the bug report template:

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the bug**
A clear and concise description of what the bug is.

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Movie Capture version: 
 - Operating system version: 
 - Capture component used: 
 - Capture settings (resolution, frame-rate, codec): 

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Videos**
If applicable, add a copy of your video or the URL

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
Closing this issue as there is nothing related to the plugin in the trace you posted.
