### ISSUE TITLE
Urgent, captures only green video on Android.

### ISSUE THREAD

**Issue by hizzlehoff** [RenderHeads/UnityPlugin-AVProMovieCapture#247]
Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the bug**

I am capturing a renderTexture at 16:9. 

The h264 video captured on Android (on a Quest Pro) only contains the green channel. I own the full version of the plugin so no watermark is applied.

If I increase the resolution of the rendertexture above 1024x576 the video signal is all scrambled.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.16f1
 - AVPro Movie Capture version: 
 - Operating system version: Windows
 - Capture component used: TextureCapture
 - Capture settings (resolution, frame-rate, codec): 24 fps, h264 mp4.

**Screenshots**
Just green video at 1024x576:
![image](https://user-images.githubusercontent.com/7126904/216939880-ff4360d6-834d-4b43-872e-b51327f1e72c.png)

Green and scrambled video at 1280x720 or higher:
![image](https://user-images.githubusercontent.com/7126904/216940856-f3d6e85e-ebeb-4ac7-955e-8bf30b1d6dbb.png)

Render texture properties
![image](https://user-images.githubusercontent.com/7126904/216940141-6a752157-d47b-4155-87af-8ed23ef0d41d.png)

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
We've responded via email for now.

**Comment by MorrisRH** [comment]
I've been unable to reproduce this using our demo scenes, specifically the "CaptureFromTexture" demo scene using the texture properties you specified. Also unable to reproduce this using the CaptureFromCamera demo scene.

We don't have access to a Quest Pro so it's quite possible that this issue is specific to that hardware, however we do have access to a device with the same GPU (Adeno 650) and that shows no issues.

**Comment by Chris-RH** [comment]
Have you tried capturing using Vulkan instead of OpenGLES?
Could you try the texture capture demo scene with some odd resolutions and see what you get?
