### ISSUE TITLE
Can't record higher than 15fps on webcam demo in Windows

### ISSUE THREAD

**Issue by Chris-RH** [RenderHeads/UnityPlugin-AVProMovieCapture#248]
(I can't seem to get anything more than 15fps on Windows using the latest version 5.1.2. Is this a limitation of the demo? I've tried the latest version of Unity, and the most recent LTS version as well.) 

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the bug**

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Movie Capture version: 
 - Operating system version: 
 - Capture component used: 
 - Capture settings (resolution, frame-rate, codec): 

**To Reproduce**

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by shealan** [comment]
Describe the bug
A clear and concise description of what the bug is.

Your Setup (please complete the following information):

Unity version: 2021.3.11f1 Personal
AVPro Movie Capture version: AVPro Movie Capture v5.1.2
Operating system version: Windows 10
Capture component used: Webcam Capture (Logitech Brio webcam
Capture settings (resolution, frame-rate, codec): Tried all options, anything more than 15fps seems impossible,.
To Reproduce
Steps to reproduce the behavior:

Loaded the demo package into my Unity project. Opened the WebcamCapture scene.
Webcam video feeds shows as expected but WebCam FPS never goes above 15 frames.
When capturing the frame rate shows as being around 30fps but the video it creates seems lower. The display says no dropped frames but the captured video is glitchy. I try the same with 60fps but the resulting video looks exactly the same. It seems to me although a file with a higher fps was created the limited fps webcam source was the same.
I have tried to adjust the Webcam Frame Rate in the script. If I change to lower, eg 5fps it goes lower, but nothing above 15fps seems to have any affect.
The computer is a high spec 64gb RAM with a 3090 graphics card.

Screenshots
![image](https://user-images.githubusercontent.com/74932/216964002-49d1ef80-d571-497b-a019-d4868fd9d266.png)
![image](https://user-images.githubusercontent.com/74932/216965839-3f3d9e70-e915-450e-ac79-1a36cf05e334.png)

**Comment by shealan** [comment]
I have done further testing and connected an HDMI to USB converter device. The video feed from that appears to show correctly at 30fps and the recorded video looks good. Any idea what could be causing the problem with the BRIO?

Is there any way of accessing/adjusting the webcam settings via the script? Using one of your other packages perhaps?

**Comment by Chris-RH** [comment]
1. What is the lighting level like, Can you make the area brighter and see if that helps?
2. Are the camera drivers up to date?
3. Try going into the camera settings and disabling things like auto exposure, "right light" etc..see if that helps?
4. Have you tried a different USB cable/slot?
5. With the HDMI converter, what FPS are you able to get up to?

**Comment by shealan** [comment]
I combined the Renderheads Live Camera package into the project I was working on. The video coming out of that is perfect using the same Brio webcam and recordings look good. This solves my problem so happy to leave it here if you want to mark as closed.

**Comment by Chris-RH** [comment]
OK, brilliant, thank you :)
