### ISSUE TITLE
Capture From Camera 360 ODS errors at higher resolutions

### ISSUE THREAD

**Issue by riiight** [RenderHeads/UnityPlugin-AVProMovieCapture#257]
"Capture From Camera 360 ODS" works if my scene is rendered at a lower resolution (up to 2048x1024), but if I go any higher than that, it will stall out and throw a number of errors such as:

- d3d11: failed to create 2D texture shader resource view id=198634 [D3D error was 887c0003]
- D3D11: Failed to create render texture primary RTV (error 0x887c003)

My scene may be considered complex as there are a number of Visual Effect Graph entities with a lot of particles. I am able to render the ODS Demo Scene at a higher resolution, so I'm guessing the issue I'm experiencing has to do with my project or the complexity of my scene. Any advice/suggestions you can give (e.g. "turn off X setting in Project Settings") would be helpful. Thanks.

**Your Setup (please complete the following information):**
 - Unity version:  2021.3.17f1
 - AVPro Movie Capture version: 5.1.3
 - Operating system version: Windows 10 
 - Capture component used: Capture From Camera 360 ODS 
 - Capture settings (resolution, frame-rate, codec): 2048x2048, 60, HEVC

**Comment by Chris-RH** [comment]
Hi @riiight 

ODS basically renders the scene ScreenWidth number of times. So if you're capturing to a 2048x2048 texture, it will render the scene 2048 times per frame! That is why it's so heavy on the GPU (and thus the CPU as the CPU has to submit all the driver commands and handle the rendering logic).
Your error makes it seem likes its running out of memory.  

1. What is your device CPU/GPU/RAM?
2. Are your GPU drivers up to date?
3. You must disable the profiler completely when using this component. This is done by opening the profiler, disabling the record option, closing the profiler, remove the tab if it is docked, then restarting Unity
4. Is it better if you run in a standalone build rather than in the editor?
5. You say those are some of the errors, can you include all of them?
6. Is it URP or HDRP?
7. What are the AA settings?
8. You could try enabling  Force GPU Flush (Capture Component Misc Settings)
9. Set Minimum Disk Space MB to -1 (Capture Component Misc Settings)

**Comment by riiight** [comment]
Thanks for your response. It looks like enabling "Force GPU Flush" and running it as a standalone build got it to work. I'll provide the info you asked for for others that may be having the same issue in the future:

What is your device CPU/GPU/RAM?
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz   4.01 GHz / RTX 3090 / 32GB

Are your GPU drivers up to date?
Yes

Is it better if you run in a standalone build rather than in the editor?
Yes. This turns out to be part of the solution.

You say those are some of the errors, can you include all of them?
- d3d11: failed to create 2D texture shader resource view id=198634 [D3D error was 887c0003]
- D3D11: Failed to create render texture primary RTV (error 0x887c003)

Is it URP or HDRP?
HDRP

What are the AA settings?
None

You could try enabling Force GPU Flush (Capture Component Misc Settings)
This was part of the solution.
