### ISSUE TITLE
 Is there a noise canceling function when recording video?

### ISSUE THREAD

**Issue by koodonghyeon** [RenderHeads/UnityPlugin-AVProMovieCapture#278]
First of all, I'm sorry that I can't speak English well.

I am recording a video using Capture from Textrue in Unity.

But the noise around me is too serious.

i want to remove this can you tell me how to remove it?

**Comment by Chris-RH** [comment]
Hi, please can you fill in all the bug report information.  It would be very helpful if you can also supply pictures of the bug you are seeing:

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the bug**
A clear and concise description of what the bug is.

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Movie Capture version: 
 - Operating system version: 
 - Capture component used: 
 - Capture settings (resolution, frame-rate, codec): 

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Videos**
If applicable, add a copy of your video or the URL

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com
