### ISSUE TITLE
Rotate screen during recording

### ISSUE THREAD

**Issue by AllenTomas** [RenderHeads/UnityPlugin-AVProMovieCapture#341]
Hi,  how to rotate screen during recording and the movie resolution ratio follow changed。
Now，I discover while I rotate the screen and the movie resolution ratio not changed, and the movie resolution ratio has deformation。
I need your help, please!

**Comment by Chris-RH** [comment]
Please fill out a full report 

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the bug**
A clear and concise description of what the bug is.

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Movie Capture version: 
 - Operating system version: 
 - Capture component used: 
 - Capture settings (resolution, frame-rate, codec): 

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Videos**
If applicable, add a copy of your video or the URL

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
I'm afraid what you're asking for is impossible. The resolution of the captured video is set at creation and cannot be changed midway through recording.
