### ISSUE TITLE
Failed to record using Offline Render in windowed mode

### ISSUE THREAD

**Issue by anhnguyenvn** [RenderHeads/UnityPlugin-AVProMovieCapture#51]
Hi,

I don't really know why recording using Offline Render in windowed mode only produces 1 frame.
Look like in CaptureBase.cs, when screen is not in fullscreen mode, you disable Vsync and this is the reason of the bug. Currently, I just simply uncheck Allow V Sync Disable in inspector of CaptureFromScreen script and the bug is fixed, but is that the correct way to fix? Why you need to turn off vSync in windowed mode? Thanks

Anh Nguyen

**Comment by AndrewRH** [comment]
Turning off vsync for offline render is just an optimisation - it allows the rendering to run as fast as it can, rather than capped at your refresh rate (usually 60fps).
It should work fine in windowed mode...I would actually expect fullscreen mode to be the one that causes problems, as switching vsync in fullscreen mode can cause the context to be recreated...

Which version of AVPro Movie Capture and Unity are you using?
Are you running in D3D11?
Do you know if you're running windowed, fullscreen-windows, or fullscreen-exclusive?

Thanks,

**Comment by anhnguyenvn** [comment]
I am using AVPro 4.3.1, Unity 2019.3.3f1 and D3D12. I recorded ok when in fullscreen exclusive, failed in windowed mode, have not tested fullscreen window yet. Thanks.

**Comment by AndrewRH** [comment]
Thanks for the extra information :)
That's strange, since mostly all of our testing is done in windowed mode.
D3D12?  Hmmm, I didn't think we supported that!  I will test it...
Thanks,

**Comment by AndrewRH** [comment]
Hi @anhnguyenvn 

Did you ever manage to get this working better or figure out the issue?

Thanks,
