### ISSUE TITLE
8K 360 video recording process is slowing down the application

### ISSUE THREAD

**Issue by sree4sree** [RenderHeads/UnityPlugin-AVProMovieCapture#64]
The 4K mode in this plugin seems to use less resources, which is nice. There were no lag issues while i am interacting with the UI's. once I start recording in 8K I can no longer control the scene or asset interfaces. I only managed to get a short, static video[our fps control cant move forward due to the lagging].

 - Unity version: 2019.1.5f1
 - AVPro Movie Capture version: 4.3.0t [Trial Version]
 - Operating system version: Windows 64 bit
 - Capture component used:  Capture from Camera 360
 - Capture settings (resolution, frame-rate, codec): 8k,30,H264

System Configuration That we have tried:-

AMD ryzen 1700x
Nvidia 1080 8GB
16 GB RAM

AMD ryzen 3700x
AMD Radeon 5600XT
16 GB RAM

**Comment by sreeforsreekanth** [comment]
Hi there, is there any way to resolve this problem...??

**Comment by AndrewRH** [comment]
Have you tried recording to HEVC instead of H264?
Did you use the Unity profiler to see where the frame time was going?
In the CaptureFromCamera360 we do re-render the scene again, so it does add quite a bit of overhead if you have a complex scene to render.   
Also our encoding path is not 100% using the GPU, so 8K definitely will be heavy for the system during a real-time capture.
