### ISSUE TITLE
As the AVProMovieCapture recording lasted too long, it froze at the end of the recording

### ISSUE THREAD

**Issue by gy751** [RenderHeads/UnityPlugin-AVProMovieCapture#68]
I have purchased your company's plug-in.After using it, a problem was found.The video is recorded in H264 and takes too long.Clicking to end recording will cause the packaged software to fail to respond and become stuck for dozens of seconds.
Is there any way to avoid this problem?
When we use an Intel integrated graphics card, does that have anything to do with it?
Are there any recommended computer configurations to use this plugin?If yes, please provide!

**Comment by AndrewRH** [comment]
Hi,

Could you give us a few more details please so that we can help solve this issue, such as:

1) Unity version
2) AVPro Movie Capture version
3) Platform and operating system version
4) Are you recording in the editor or in a standalone build when this issue happens?
5) How long does it get stuck for?  
6) After it gets stuck does it complete correctly and produce a valid video file?
7) What are the specs of the machine?
8) What resolution and frame-rate are you capturing at?
9) Which component are you using to capture?

Thanks,

**Comment by gy751** [comment]
> 你好
> 
> 您能否再提供一些详细信息，以便我们帮助解决此问题，例如：
> 
> 1. Unity版本
> 2. AVPro Movie Capture版本
> 3. 平台和操作系统版本
> 4. 发生此问题时，您是在编辑器中录制还是在独立版本中录制？
> 5. 卡多长时间？
> 6. 卡住后，它能否正确完成并产生有效的视频文件？
> 7. 机器的规格是什么？
> 8. 您以什么分辨率和帧速率捕获？
> 9. 您正在使用哪个组件来捕获？
> 
> 谢谢，

Untiy version 2019.1.12
AVPro Movie Capture Version 4.3.3
window 10
The phenomenon of jamming occurs in the packaged independent version, about an hour after the recording will appear.
Stuck for about a few dozen seconds
After being stuck, it will return to normal after a while and can generate valid video files
The resolution is 1920x1080 25FPS
CaptureFromCamera USES this component

Use the computer configuration as follows
core i7-8700 6 nuclear
8 gb of memory
Intel UHD630 graphics card

**Comment by AndrewRH** [comment]
@gy751  Did you find the cause of this issue?
