### ISSUE TITLE
Save RGBA image, but the aliasing of the edge is obvious in 1080P.

### ISSUE THREAD

**Issue by chaserat** [RenderHeads/UnityPlugin-AVProMovieCapture#72]
**Describe the bug**
With the RGBA "save" function, the png atlas has gained. But the aliasing phonemenon occurs obviously. Shall I take some measures to solve or reduce this kind of problems?

**Your Setup (please complete the following information):**
 - Unity version:  2019.2.12f1
 - AVPro Movie Capture version: 4.3.3
 - Operating system version: windows
 - Capture component used: (capture from camera)
 - Capture settings (resolution, frame-rate, codec): 

**Screenshots**
![image](https://user-images.githubusercontent.com/30485904/92573687-b9015d00-f2b8-11ea-81c5-fee30a5908c9.png)

**Comment by AndrewRH** [comment]
Hi,

What exactly do you mean by "RGBA save function" - just writing out a PNG image sequence?

Are you relying on capturing transparency?

Can you show what the source image looks like so we can compare the aliasing?

What are you capturing that is aliasing?  I can't tell if that's geometry or a texture or what.

If you are using MSAA in your main camera and you are using Capture From Camera, then make sure you have the correct MSAA value set in the capture component.

Thanks,

**Comment by chaserat** [comment]
Yeah, my setting is as follows:

**Comment by chaserat** [comment]
Thank U! "Disable MSAA & a higher resolution" is useful, but it take much
computation, which caused the frame rate reducing from 24 to 15 FPS.
Does this means a better GPU is needed?


Andrew <notifications@github.com> 于2020年9月10日周四 下午8:35写道：

**Comment by AndrewRH** [comment]
I'm afraid I can't really offer more help without more information.  I've asked a few questions to try to get more information so that I can give you a better answer.  I'm not sure what you're doing or how you're trying to do it, so I don't know whether a better GPU is required.  I don't know what GPU you're using in the first place.  Super sampling is very expensive.  You could also look at using image-based anti-aliasing such as FXAA or TXAA.
