### ISSUE TITLE
Blur issue in captured videos

### ISSUE THREAD

**Issue by shilpa0511** [RenderHeads/UnityPlugin-AVProMovieCapture#77]
Hi Team,

I am facing the below issues in windows. Kindly suggest any solution.
1. Images are blurred in the captured videos. PFB the images of scene view and captured video screenshot image. The following are the settings which I used.
Codec - HEVC
Resolution - 3840x2160
CubeMap - 2048
Antialiasing - 2x
![Scene](https://user-images.githubusercontent.com/72505032/96717844-bff5b200-13c4-11eb-9ffe-e57f9a18f862.png)
![CapturedVideoScreenshot](https://user-images.githubusercontent.com/72505032/96719642-47dcbb80-13c7-11eb-9c24-d4c7b98fc047.png)
2. If I increase cubemap resolution to max, application lags and crashes.
3.For HEVC code, upto 3840x2160 is working and if I increase the resolution, captured video file is empty.

**Your Setup (please complete the following information):**
 - Unity version: 2019.1.5f1
 - AVPro Movie Capture version: AVPro Movie Capture - 4.4.1
 - Operating system version: Windows 10
 - Capture settings (resolution, frame-rate, codec): Mentioned above.
PC settings
- CPU - Ryzen 3700x
- GPU - Raedon 5600xt 6GB
- ram - 16GB 3200mhz speed

**Comment by AndrewRH** [comment]
Hi,

Thanks for posting the issue.

So first of all 3840x2160 isn't much resolution for a 360 video, especially one that contains text and thin lines.  Consider that your image is almost that resolution itself, and the 360 video has to contain about 6x more area, I'm not too surprised that it looks blurry.

Unfortunately AMD's hardware has weak video encoders (compared to Intel and Nvidia), so that is why it can't do a HEVC encode higher than 3840x2160.  You may want to consider encoding to a PNG sequence instead, and then using a software encoder (such as FFMPEG) to recompress the video.  This will allow you to render out a much higher resolution, which even if you downsample it will get you a better quality.

I'm not sure why setting the cubemap resolution is causing a problem.  Cubemaps do use a lot of GPU memory, so you may not be able to do 8K cubemaps, but I would think you could at least do 4K (4096) cubemaps.

I hope the two suggestions above help you.

Thanks,

**Comment by sunilsingha** [comment]
> Hi,
> 
> Thanks for posting the issue.
> 
> So first of all 3840x2160 isn't much resolution for a 360 video, especially one that contains text and thin lines. Consider that your image is almost that resolution itself, and the 360 video has to contain about 6x more area, I'm not too surprised that it looks blurry.
> 
> Unfortunately AMD's hardware has weak video encoders (compared to Intel and Nvidia), so that is why it can't do a HEVC encode higher than 3840x2160. You may want to consider encoding to a PNG sequence instead, and then using a software encoder (such as FFMPEG) to recompress the video. This will allow you to render out a much higher resolution, which even if you downsample it will get you a better quality.
> 
> I'm not sure why setting the cubemap resolution is causing a problem. Cubemaps do use a lot of GPU memory, so you may not be able to do 8K cubemaps, but I would think you could at least do 4K (4096) cubemaps.
> 
> I hope the two suggestions above help you.
> 
> Thanks,

Hi Andrew,

we also have Nvidia 1080 8GB graphics card and our app crashes if i go with higher resolution + 4K cubemap. And also while capturing the gameplay lags a lot. And hence we had to use 3840x2160 resolution.
while capturing with maxed cubemap, the memory increases and it crashes the app. we have 32gb memory. 
Is there a way to limit the memory consumption?

BR,
Sunil

**Comment by sunilsingha** [comment]
Hi Andrew,

Could you please elaborate "You may want to consider encoding to a PNG sequence instead, and then using a software encoder (such as FFMPEG) to recompress the video."
Is this a settings inside AVPRO capture?

BR,
Sunil

**Comment by AndrewRH** [comment]
> Hi Andrew,
> 
> Could you please elaborate "You may want to consider encoding to a PNG sequence instead, and then using a software encoder (such as FFMPEG) to recompress the video."
> Is this a settings inside AVPRO capture?
> 
> BR,
> Sunil

Yes you can select to encode to an image sequence instead of a video file:
![image](https://user-images.githubusercontent.com/5418126/96921726-d70cd080-14a6-11eb-879d-ec69c888c183.png)

Once the PNG files are generated you can encode them to a video using the free tool FFMPEG with a command-line for example:

ffmpeg -y -r 60 -i frame-%%06d.png -pix_fmt yuv420p -preset medium -crf 18 output.mp4

**Comment by AndrewRH** [comment]
> we also have Nvidia 1080 8GB graphics card and our app crashes if i go with higher resolution + 4K cubemap. And also while capturing the gameplay lags a lot. And hence we had to use 3840x2160 resolution.
> while capturing with maxed cubemap, the memory increases and it crashes the app. we have 32gb memory.
> Is there a way to limit the memory consumption?

Oh you're capturing during gameplay?  I didn't realise that....The 360 capture is not really suitable for that because it's very expensive operation.  It's more intended for offline capturing:
![image](https://user-images.githubusercontent.com/5418126/96922639-03751c80-14a8-11eb-8314-8efd76811858.png)

A 4K cubemap uses about 400MB of RAM, and the GPU usually has to have copied of them for pipelining, so expect around 1.2GB of GPU memory just for those.   Your GPU should be fine though with 8GB, so I'm not sure why it's crashing.  This sort of capturing will be far too slow though for real-time anyway.  I'm not sure why you need to capture in realtime, but perhaps you can consider an offline capture.

Thanks,

**Comment by sunilsingha** [comment]
> > we also have Nvidia 1080 8GB graphics card and our app crashes if i go with higher resolution + 4K cubemap. And also while capturing the gameplay lags a lot. And hence we had to use 3840x2160 resolution.
> > while capturing with maxed cubemap, the memory increases and it crashes the app. we have 32gb memory.
> > Is there a way to limit the memory consumption?
> 
> Oh you're capturing during gameplay? I didn't realise that....The 360 capture is not really suitable for that because it's very expensive operation. It's more intended for offline capturing:
> ![image](https://user-images.githubusercontent.com/5418126/96922639-03751c80-14a8-11eb-8314-8efd76811858.png)
> 
> A 4K cubemap uses about 400MB of RAM, and the GPU usually has to have copied of them for pipelining, so expect around 1.2GB of GPU memory just for those. Your GPU should be fine though with 8GB, so I'm not sure why it's crashing. This sort of capturing will be far too slow though for real-time anyway. I'm not sure why you need to capture in realtime, but perhaps you can consider an offline capture.
> 
> Thanks,

Thanks for the suggestion, we tried the offline render option initially but the audio is distorted with this option. The audio plays for some time and then suddenly stops and starts playing again.
our main objective, we have a room with 4 walls and we use 4 AVPRO video players on those walls to play videos and there are bunch of other stuff we overlay on those wall. So with AVPRO capture, we want to record a full 360 video.  
please let me know what is the solution where i can get a very good quality output. thanks.
