### ISSUE TITLE
Sometimes doesn't encode the exact number of frames expected

### ISSUE THREAD

**Issue by kahnivore** [RenderHeads/UnityPlugin-AVProMovieCapture#90]
From keeping (added sample project to bucket):

We're experiencing a problem with AVPro Movie Capture 4.6.0. We utilize the offline mode in order to make a faster-than-realtime cutscene recording. Recording is always configured with precise duration (currently we test at 10 seconds, 30 FPS), and it's of highest importance that the resulting video has the expected frame count. This is the case when capturing video in Unity Editor, however in a Windows standalone build the amount of frames in the video is variable and fluctuates between 300 and 303 frames, in this configuration. To get the frame count, I use ffprobe with the following arguments:

-v error -select_streams v:0 -show_entries stream=nb_frames -of default=nokey=1:noprint_wrappers=1

I've recreated our use conditions in a blank project, and used unmodified Movie Capture plugin, and still I get a stable frame count only in editor, while in build it varies.

Thus, two questions: why is this happening and what can we do to guarantee consistent video output in standalone builds?

Another thing is the right way to use the StopMode property. If I set it to 300 and look at the CaptureStats property after the video is recorded, NumEncodedFrames will be equal to 297, FramesTotal - 300, while ffprobe will tell that the video contains 299 frames (even when capturing from editor, without any fluctuations). What explains the 3 frame Encoded/Total difference and 2 frame Encoded/Actual(ffprobe)? How can I make it encode precisely 300 frames?

**Comment by AndrewRH** [comment]
This issue is fixed in 4.6.2 so I will close this issue.

It should be noted that (at least on Windows) when recording AAC audio it may not be possible to get the audio track to the exact duration of the video track as correct rendering of AAC requires some initial priming and padding data.  If this is important then you may prefer to use the FLAC codec as it will always have the perfect duration matching the video track length when encoding to a fixed number of frames.

Thanks,
