### ISSUE TITLE
Possible to Swap out Audio Listener and/or Game Camera while recording?

### ISSUE THREAD

**Issue by Sbrenman** [RenderHeads/UnityPlugin-AVProMovieCapture#92]
Is it possible to swap out one audio listener and CaptureAudioFromAudioLIstener component for a different one while recording (using UnityAudioCapture)?

Secondly, is it possible to swap out one game camera for another game camera while recording (using CapturefromCamera)?

**Comment by AndrewRH** [comment]
> Is it possible to swap out one audio listener and CaptureAudioFromAudioLIstener component for a different one while recording (using UnityAudioCapture)?

Yes this should be possible.  I assume this is needed because you are switching scenes?   You can set the new CaptureAudioFromAudioListener component on the CaptureFrom component by using the UnityAudioCapture property:

```
capture.UnityAudioCapture = myNewAudioCapture;
```

I'm not sure if that may cause a small audio glitch though.  Alternatively if you're using Windows you can record directly from your system speakers by selecting a loopback audio device, eliminating the need to attach to an AudioListener in Unity.  You can do this via scripting:

   ```
            {
                Device firstLoopbackDevice = null;
                foreach (Device device in DeviceManager.AudioInputDevices)
                {
                    if (device.Name.Contains("(loopback)"))
                    {
                        firstLoopbackDevice = device;
                        break;
                    }
                }
                if (firstLoopbackDevice != null)
                {
                    _capture.AudioCaptureSource = AudioCaptureSource.Microphone;
                    _capture.ForceAudioInputDeviceIndex = firstLoopbackDevice.Index;
                }
            }
```

> Secondly, is it possible to swap out one game camera for another game camera while recording (using CapturefromCamera)?

Yes you can do this in two ways.  First you could use the CameraSelector component which you can set to automatically find a suitable camera in your scene, or you can use it to switch to a specific camera.  Otherwise, you can just set the new camera directly in the capture component:

```
            CaptureFromCamera.SetCamera(myCamera, useContributingCameras:true);
```

I hope that helps but do let us know if you have any other questions.

**Comment by Sbrenman** [comment]
Thanks for this quick response! I will give this a try.

**Comment by Sbrenman** [comment]
Hi Andrew, these solutions seem to be working - thanks!

I am also wondering if it's possible to change the FilenamePrefix on a capture script once a recording has already started. 
I tried reassigning the FilenamePrefix after a recording has started, but it did not update the final output path when the recording stopped. 

Thank you

**Comment by AndrewRH** [comment]
> I am also wondering if it's possible to change the FilenamePrefix on a capture script once a recording has already started.
> I tried reassigning the FilenamePrefix after a recording has started, but it did not update the final output path when the recording stopped.

I'm not sure what you mean?  Once the recording starts the file is locked, so you can't change it's name until recording has stopped.  The filename must be set before recording starts.

**Comment by Sbrenman** [comment]
Go it. Thanks for the confirmation

**Comment by Sbrenman** [comment]
Hi @AndrewRH, I have another question. 

Currently, for the case in which I need to change the filename of a recording after it has started recording, my solution is to copy the file that AVPro capture has written for me into a new file with my updated name, and then delete the old file. 

This works, except that I get a Debug error in Mp4FileProcessing, line 47 (bolded), because I have already deleted the old filepath.

I don't want to comment out your debug log here because if I ever update the asset I will have to remember to redo the changes. I have been able to side step this debug log by waiting for 5 seconds before deleting the original file recording but it's a bit of a gamble that 5 seconds will be enough time. Is there any way for me to retrieve an event or bool letting me know that all the processing is finished and it's safe to delete the recording file?    
       
Thanks

 public static ManualResetEvent ApplyFastStartAsync(string filePath, bool keepBackup)
        {
            if (!File.Exists(filePath))
            {
                **Debug.LogError("File not found: " + filePath);**
                return null;
            }

**Comment by AndrewRH** [comment]
Yes there are a couple of options.  Firstly you could just call:

		StopCapture(skipPendingFrames:false, ignorePendingFileWrites:true);

This will block and not return until the capture is totally completed, including the post operations.   This is the simplest fix, but it can make your app freeze while this happens.  The length of freeze time will depend on the video you're encoding, but it should generally be less than a second.

The other option would be to subscribe to the FileWriteHandler so that you can find out when the file writing is complete.  This is done like:



		private FileWritingHandler _fileWritingHandler = null;

		void Start()
		{
			// Subscribe to event
			_capture.BeginFinalFileWritingAction += OnBeginFinalFileWriting;
		}

		private void OnBeginFinalFileWriting(FileWritingHandler handler)
		{
			_fileWritingHandler = handler;
		}

		void Update()
		{
			if (_fileWritingHandler.IsFileReady())
			{
				_fileWritingHandler = null;
				// Now you can allow the next capture to begin
			}
		}

		void OnDestroy()
		{
			if (_fileWritingHandler)
			{
				_fileWritingHandler.Dispose();
				_fileWritingHandler = null;
			}
		}

Hope that helps.
